### ISSUE TITLE
Does gh-pages example really works?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [codepo8/gridnav#4]
I'm testing it right now and neither Cursor Keys or WASD doesn't work.

No console errors neither resource scripts blocked.

**Comment by codepo8** [comment]
Might be a codepen issue. What browser/OS? And do the examples here work? Also, which codepen example? I use JSBin in the blog post. The first example is not meant to have the functionality yet, the [second one](http://output.jsbin.com/mafeko/) works fine here. 
Technically this is a blog post issue, not for here.

**Comment by julianxhokaxhiu** [comment]
Windows 10 Anniversary Update
Chrome 52.0.2743.116 stable 64bit
URL: https://codepo8.github.io/gridnav

You are right sorry, I read only `codep` and I thought it was on codepen :)

Also, this other URL http://output.jsbin.com/mafeko/ doesn't work. Same behavior. Nothing happen :\

**Comment by codepo8** [comment]
Fixed it - this was the pull request that broke it. Keypress doesn't seam to work with windows, so I changed it back to keyup

**Comment by julianxhokaxhiu** [comment]
Thank you :) I'll try to test it later, in order to provide you a feedback

**Comment by julianxhokaxhiu** [comment]
Tested and works! Although I thought that events like scrolling in the page were prevented. If I used the "down" key or "up" key, the page scrolls and it's not nice. Can you fix this as well please?

**Comment by julianxhokaxhiu** [comment]
What about the proposed fix?

**Comment by julianxhokaxhiu** [comment]
Hi @codepo8 any update on this?
